spring:
  application:
    name: quotes
    formattedVersion: 1.0.0
  datasource:
    username: admin
    password: Meg~7+inO
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/quotes
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: validate
    show-sql: true
  freemarker:
    expose-request-attributes: true
  mail:
    host: smtp.gmail.com
    username: quotesfromdb@gmail.com
    password: 
    port: 465
    protocol: smtps
server:
  port: 3000

upload:
  path: /app/uploads

mail:
  debug: false
