spring:
  application:
    name: quotes
    formattedVersion: 1.0.0
  datasource:
    username: admin
    password: Meg~7+inO
    url: jdbc:postgresql://localhost:5432/quotes
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    show-sql: false
  freemarker:
    expose-request-attributes: true
  mail:
    host: smtp.gmail.com
    username: quotesfromdb@gmail.com
    password: 1fWEikNBV*yxZZq
    port: 465
    protocol: smtps
server:
  port: 8080

upload:
  path: /app/uploads

mail:
  debug: false